/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AlexPackage;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author alexander.rejep819
 */
public class scores extends javax.swing.JFrame {

    /**
     * Creates new form scores
     */
    public scores() throws IOException{
        initComponents();
         jLabel1.setText("Game High Scores");
         //dummy varible
        BufferedReader readFile = null;
        String reading = "";
        int intReading = 0;
        //array list to store the data from the file 
        ArrayList myArrayList= new ArrayList<Integer>();

        //OptionPane to ask the reader what local file they would like the program to read
        //NO SAFE GAURD FOR THE NULL POINTER EXCEPTION, THIS HAS BEEN APPROVED BY MR.V
       
        //Opens the text file and attaches a BufferedReader
        readFile = new BufferedReader(new FileReader("HighScoresAlex.txt"));
               
        //do loop to continue to get data until theres no more lines to read
        do {
            //sets the line of the external file to the dummy varible
            reading = readFile.readLine();
            //if statment to not get a "null" line when printing the array 
            if (reading != null) {
                //adds line to array
                try {
                intReading = Integer.parseInt(reading);
                }catch (NumberFormatException e){
                        }
                myArrayList.add(intReading);
            }
        } while (reading != null);
        //closes text file as thats proper coding 
        readFile.close();
        //prints the text, uses for loop to print each line on its own line
        for (int i = 0; i < myArrayList.size(); i++) {
            System.out.println(myArrayList.get(i));
        }
         selectionSort(myArrayList);
         System.out.println("These numbers in a sorted list are: " + myArrayList);
         highScore1.setText(String.valueOf(myArrayList.get(0)));
         highScore2.setText(String.valueOf(myArrayList.get(1))); 
         highScore3.setText(String.valueOf(myArrayList.get(2))); 
    }

    public static void selectionSort(ArrayList myArrayList) {
        int smallest;
         for (int i = 0; i < myArrayList.size() - 1; i++) {
                smallest = i;
                //see if there is a smaller number further in the array
                for (int index = i + 1; index < myArrayList.size(); index++) {
                    //the conditions in this if statement are switched (compared to the previous statement) to make it descending 
                    if ((Integer) myArrayList.get(smallest) < (Integer) myArrayList.get(index)) {
                        swap(myArrayList, smallest, index);
                    }
                }
        }
    }
    
    public static void swap(ArrayList array2, int first, int second) {
        int hold = (Integer) array2.get(first);
        array2.set(first, array2.get(second));
        array2.set(second, hold);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        highScore1 = new javax.swing.JLabel();
        highScore2 = new javax.swing.JLabel();
        highScore3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(600, 600));
        setSize(new java.awt.Dimension(600, 600));
        getContentPane().setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(thefaultinourbaldspot.TheFaultInOurBaldSpotApp.class).getContext().getResourceMap(scores.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 580, 80);

        highScore1.setFont(resourceMap.getFont("highScore1.font")); // NOI18N
        highScore1.setText(resourceMap.getString("highScore1.text")); // NOI18N
        highScore1.setName("highScore1"); // NOI18N
        getContentPane().add(highScore1);
        highScore1.setBounds(10, 109, 80, 20);

        highScore2.setFont(resourceMap.getFont("highScore2.font")); // NOI18N
        highScore2.setText(resourceMap.getString("highScore2.text")); // NOI18N
        highScore2.setName("highScore2"); // NOI18N
        getContentPane().add(highScore2);
        highScore2.setBounds(10, 147, 80, 20);

        highScore3.setFont(resourceMap.getFont("highScore3.font")); // NOI18N
        highScore3.setText(resourceMap.getString("highScore3.text")); // NOI18N
        highScore3.setName("highScore3"); // NOI18N
        getContentPane().add(highScore3);
        highScore3.setBounds(10, 185, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                new scores().setVisible(true);
                 } catch (IOException ex) {
                    Logger.getLogger(scores.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel highScore1;
    private javax.swing.JLabel highScore2;
    private javax.swing.JLabel highScore3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
