
/*
 * Written by Mr. van Straten
 * May 21, 2019
 * JFrameImages
 * This is a demo program for images and collision detection
 */
package JohnPackage;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class JohnF extends javax.swing.JFrame {

    int mx, my;
    boolean boneSawClick = false;
    boolean cutClick = false;

    public JohnF() {
        initComponents();
        //Initialize the label with the scaled image icon
        myInitComponents(background);
        hurt.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boneSaw = new javax.swing.JLabel();
        cutBox = new javax.swing.JLabel();
        hurt = new javax.swing.JLabel();
        health = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        lungs = new javax.swing.JLabel();
        ribs = new javax.swing.JLabel();
        heart = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N
        setSize(new java.awt.Dimension(1080, 720));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        boneSaw.setText("boneSaw");
        boneSaw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                boneSawMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                boneSawMouseMoved(evt);
            }
        });
        boneSaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boneSawMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boneSawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boneSawMouseReleased(evt);
            }
        });
        getContentPane().add(boneSaw);
        boneSaw.setBounds(10, 430, 50, 150);

        cutBox.setText("cutBox");
        cutBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cutBoxMouseExited(evt);
            }
        });
        getContentPane().add(cutBox);
        cutBox.setBounds(430, 310, 10, 70);

        hurt.setText("hurt");
        getContentPane().add(hurt);
        hurt.setBounds(20, 80, 120, 130);

        health.setText("Health");
        getContentPane().add(health);
        health.setBounds(30, 10, 71, 73);

        time.setText("Time");
        getContentPane().add(time);
        time.setBounds(1000, 0, 70, 90);
        time.getAccessibleContext().setAccessibleName("wallLabel");
        time.getAccessibleContext().setAccessibleDescription("");

        lungs.setText("Lungs");
        getContentPane().add(lungs);
        lungs.setBounds(600, 80, 110, 40);

        ribs.setText("Ribs");
        getContentPane().add(ribs);
        ribs.setBounds(350, 280, 410, 400);

        heart.setText("heart");
        getContentPane().add(heart);
        heart.setBounds(750, 70, 70, 70);

        background.setText("background");
        getContentPane().add(background);
        background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //check if a collision between images is occurring
    private boolean checkCollision(javax.swing.JLabel _lbl, int _x, int _y) {
//creating a temporary rectangle with (x, y) coordinates equal to where image is trying to move
//also same width and height as original
        Rectangle rect = new Rectangle(_lbl.getBounds().x + _x, _lbl.getBounds().y + _y, _lbl.getWidth(), _lbl.getHeight());

//check if temporary rectangle intersect with wallLabel        
        if (rect.intersects(time.getBounds())) {
            return true;
        } else {
            return false;
        }
    }

    //checks which key is pressed and moves image if no collision is detected
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //prints KeyCode for the key pressed
        // System.out.println(evt.getKeyCode());

        //up key pressed
        if (evt.getKeyCode() == 32) {
            if (boneSawClick == true) {
                boneSawClick = false;
                boneSaw.setLocation(10, 430);
            }
        }
        //down key pressed
        if (evt.getKeyCode() == 40) {
            if (!checkCollision(health, 0, 10)) {
                health.setLocation(health.getLocation().x, health.getLocation().y + 10);
            }
        }
        //left key pressed
        if (evt.getKeyCode() == 37) {
            if (!checkCollision(health, -10, 0)) {
                health.setLocation(health.getLocation().x - 10, health.getLocation().y);
            }
        }
        //right key pressed
        if (evt.getKeyCode() == 39) {
            if (!checkCollision(health, 10, 0)) {
                health.setLocation(health.getLocation().x + 10, health.getLocation().y);
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void moveTool() {
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();
        if (boneSawClick == true) {
            boneSaw.setLocation((mx - 28), (my - 32));
        }
    }

    private void injured() {
        hurt.show();
    }

    private void boneSawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseClicked
//        setCursor(Toolkit.getDefaultToolkit().createCustomCursor(
//                new ImageIcon("JSumBoneSaw.png").getImage(),
//                new Point(0, 0), "custom cursor"));
        boneSawClick = true;
        int counter = 0;
        counter++;
        if (counter > 1) {
            injured();
        }
    }//GEN-LAST:event_boneSawMouseClicked

    private void boneSawMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseMoved
        moveTool();
    }//GEN-LAST:event_boneSawMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        moveTool();
    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        moveTool();
    }//GEN-LAST:event_formMouseDragged

    private void boneSawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseDragged
        moveTool();
    }//GEN-LAST:event_boneSawMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void cutBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBoxMouseExited
        if (cutClick == true) {
            injured();
        }
    }//GEN-LAST:event_cutBoxMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased

    }//GEN-LAST:event_formMouseReleased

    private void boneSawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMousePressed
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();
            System.out.println("Hello");
        if (mx > 400 & mx < 450 & my < 350 & my > 290) {
            cutClick = true;
            System.out.println("Hellooooo");
        }
        else if (boneSawClick == true) {
            injured();
        }
    }//GEN-LAST:event_boneSawMousePressed

    private void boneSawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseReleased
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();
        System.out.println("Bone Saw released");
         System.out.println(cutClick);
        if (cutClick == true ) {
            if (mx > 400 & mx < 450 & my > 360 & my < 500 ) {
                System.out.println("Awesome");
                cutBox.hide();
            }
        }
    }//GEN-LAST:event_boneSawMouseReleased

    /**
     * Creates new form NewJFrame
     */
//Initializes the labels with their images
    public void myInitComponents(javax.swing.JLabel jLabel1) {
        //Initialize a Buffered Image
        BufferedImage img = null;

        //same as above, but in a condensed version
        try {

            background.setIcon(new ImageIcon((ImageIO.read(new File("JSumBackground.png"))).getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH)));
            ribs.setIcon(new ImageIcon((ImageIO.read(new File("JSumRibs.png"))).getScaledInstance(ribs.getWidth(), ribs.getHeight(), Image.SCALE_SMOOTH)));
            cutBox.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox.getWidth(), cutBox.getHeight(), Image.SCALE_SMOOTH)));
            boneSaw.setIcon(new ImageIcon((ImageIO.read(new File("JSumBoneSaw.png"))).getScaledInstance(boneSaw.getWidth(), boneSaw.getHeight(), Image.SCALE_SMOOTH)));
            hurt.setIcon(new ImageIcon((ImageIO.read(new File("blood.png"))).getScaledInstance(hurt.getWidth(), hurt.getHeight(), Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            Logger.getLogger(JohnF.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JohnF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel boneSaw;
    private javax.swing.JLabel cutBox;
    private javax.swing.JLabel health;
    private javax.swing.JLabel heart;
    private javax.swing.JLabel hurt;
    private javax.swing.JLabel lungs;
    private javax.swing.JLabel ribs;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
