
/*
 * Written by Mr. van Straten
 * May 21, 2019
 * JFrameImages
 * This is a demo program for images and collision detection
 */
package JohnPackage;

import java.awt.Component;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class JohnF extends javax.swing.JFrame {

    int mx, my;
    boolean boneSawClick = false;
    boolean cutClick = false;
    boolean cutClick2 = false;
    boolean cutClick3 = false;
    boolean cutClick4 = false;
    boolean cutClick5 = false;
    boolean cutClick6 = false;
    int healthValue = 100;

    private void injured() {
        Timer injuredTimer = new Timer();
        TimerTask stopInjured = new TimerTask() {
            public void run() {
                hurt.setVisible(false);
            }

        };
        injuredTimer.schedule(stopInjured, 500);
        System.out.println("injured");
        healthValue = healthValue - 5;
        healthBar.setValue(healthValue);
        hurt.show();
    }

    private void success() {
        Timer cutTimer = new Timer();
        TimerTask stopCut = new TimerTask() {
            public void run() {
                cut.setVisible(false);
            }
        };
        cutTimer.schedule(stopCut, 500);
        cut.setVisible(true);
    }

    public JohnF() {
        initComponents();
        healthBar.setValue(100);
        int health = 100;
        //Initialize the label with the scaled image icon
        myInitComponents(background);
        hurt.hide();
        cut.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boneSaw = new javax.swing.JLabel();
        healthBar = new javax.swing.JProgressBar();
        cutBox = new javax.swing.JLabel();
        hurt = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        lungs = new javax.swing.JLabel();
        heart = new javax.swing.JLabel();
        cutBox2 = new javax.swing.JLabel();
        cutBox3 = new javax.swing.JLabel();
        cutBox4 = new javax.swing.JLabel();
        cutBox5 = new javax.swing.JLabel();
        cutBox6 = new javax.swing.JLabel();
        ribs = new javax.swing.JLabel();
        cut = new javax.swing.JLabel();
        boneSawLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setName("mainFrame"); // NOI18N
        setSize(new java.awt.Dimension(1080, 720));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        boneSaw.setText("boneSaw");
        boneSaw.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                boneSawMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                boneSawMouseMoved(evt);
            }
        });
        boneSaw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boneSawMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                boneSawMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                boneSawMouseReleased(evt);
            }
        });
        getContentPane().add(boneSaw);
        boneSaw.setBounds(10, 430, 50, 150);
        getContentPane().add(healthBar);
        healthBar.setBounds(20, 10, 148, 14);

        cutBox.setText("cutBox");
        cutBox.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cutBoxMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cutBoxMouseMoved(evt);
            }
        });
        cutBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cutBoxFocusLost(evt);
            }
        });
        cutBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cutBoxMouseExited(evt);
            }
        });
        getContentPane().add(cutBox);
        cutBox.setBounds(430, 310, 10, 70);

        hurt.setText("hurt");
        getContentPane().add(hurt);
        hurt.setBounds(20, 80, 120, 130);

        time.setText("Time");
        getContentPane().add(time);
        time.setBounds(990, 10, 70, 90);
        time.getAccessibleContext().setAccessibleName("wallLabel");
        time.getAccessibleContext().setAccessibleDescription("");

        lungs.setText("Lungs");
        getContentPane().add(lungs);
        lungs.setBounds(990, 150, 50, 40);

        heart.setText("heart");
        getContentPane().add(heart);
        heart.setBounds(990, 80, 70, 70);

        cutBox2.setText("cutBox2");
        cutBox2.setMaximumSize(new java.awt.Dimension(40, 16));
        cutBox2.setMinimumSize(new java.awt.Dimension(40, 16));
        cutBox2.setPreferredSize(new java.awt.Dimension(40, 16));
        cutBox2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cutBox2MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cutBox2MouseMoved(evt);
            }
        });
        cutBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cutBox2MouseExited(evt);
            }
        });
        getContentPane().add(cutBox2);
        cutBox2.setBounds(410, 440, 10, 80);

        cutBox3.setText("jLabel1");
        cutBox3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cutBox3MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cutBox3MouseMoved(evt);
            }
        });
        cutBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cutBox3MouseExited(evt);
            }
        });
        getContentPane().add(cutBox3);
        cutBox3.setBounds(460, 570, 10, 90);

        cutBox4.setText("cutBox4");
        cutBox4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cutBox4MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cutBox4MouseMoved(evt);
            }
        });
        getContentPane().add(cutBox4);
        cutBox4.setBounds(660, 310, 10, 70);

        cutBox5.setText("cutBox5");
        cutBox5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cutBox5MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cutBox5MouseMoved(evt);
            }
        });
        getContentPane().add(cutBox5);
        cutBox5.setBounds(670, 440, 10, 80);

        cutBox6.setText("CutBox6");
        cutBox6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cutBox6MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cutBox6MouseMoved(evt);
            }
        });
        getContentPane().add(cutBox6);
        cutBox6.setBounds(640, 570, 10, 90);

        ribs.setText("Ribs");
        getContentPane().add(ribs);
        ribs.setBounds(350, 270, 410, 400);

        cut.setText("cut");
        getContentPane().add(cut);
        cut.setBounds(160, 90, 110, 110);

        boneSawLabel.setForeground(new java.awt.Color(255, 0, 51));
        boneSawLabel.setText("BONE SAW");
        getContentPane().add(boneSawLabel);
        boneSawLabel.setBounds(5, 580, 70, 16);

        background.setText("background");
        getContentPane().add(background);
        background.setBounds(0, 0, 1080, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //check if a collision between images is occurring
    private boolean checkCollision(javax.swing.JLabel _lbl, int _x, int _y) {
//creating a temporary rectangle with (x, y) coordinates equal to where image is trying to move
//also same width and height as original
        Rectangle rect = new Rectangle(_lbl.getBounds().x + _x, _lbl.getBounds().y + _y, _lbl.getWidth(), _lbl.getHeight());

//check if temporary rectangle intersect with wallLabel        
        if (rect.intersects(time.getBounds())) {
            return true;
        } else {
            return false;
        }
    }

    //checks which key is pressed and moves image if no collision is detected
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        //prints KeyCode for the key pressed
        // System.out.println(evt.getKeyCode());

        //up key pressed
        if (evt.getKeyCode() == 32) {
            if (boneSawClick == true) {
                boneSawClick = false;
                boneSaw.setLocation(10, 430);
            }
        }
        //down key pressed
        if (evt.getKeyCode() == 40) {
            if (!checkCollision(background, 0, 10)) {
                background.setLocation(background.getLocation().x, background.getLocation().y + 10);
            }
        }
        //left key pressed
        if (evt.getKeyCode() == 37) {
            if (!checkCollision(background, -10, 0)) {
                background.setLocation(background.getLocation().x - 10, background.getLocation().y);
            }
        }
        //right key pressed
        if (evt.getKeyCode() == 39) {
            if (!checkCollision(background, 10, 0)) {
                background.setLocation(background.getLocation().x + 10, background.getLocation().y);
            }
        }
    }//GEN-LAST:event_formKeyPressed

    private void moveTool() {
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();
        if (boneSawClick == true) {
            boneSaw.setLocation((mx - 32), (my - 30));
        }
    }


    private void boneSawMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseClicked
//        setCursor(Toolkit.getDefaultToolkit().createCustomCursor(
//                new ImageIcon("JSumBoneSaw.png").getImage(),
//                new Point(0, 0), "custom cursor"));
        boneSawClick = true;
//        int counter = 0;
//        counter++;
    }//GEN-LAST:event_boneSawMouseClicked

    private void boneSawMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseMoved
        moveTool();
    }//GEN-LAST:event_boneSawMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        moveTool();
    }//GEN-LAST:event_formMouseMoved

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        moveTool();
    }//GEN-LAST:event_formMouseDragged

    private void boneSawMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseDragged
        moveTool();
    }//GEN-LAST:event_boneSawMouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();

        System.out.println(mx + ", " + my);
    }//GEN-LAST:event_formMouseClicked

    private void cutBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBoxMouseExited
        System.out.println("Exited");
        if (cutClick == true & boneSawClick == true) {
            injured();
        }
    }//GEN-LAST:event_cutBoxMouseExited

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();
        if (boneSawClick == true) {
            if (mx > 433 & mx < 449 & my < 340 & my > 320) {
                cutClick = true;
            } else if (mx > 414 & mx < 426 & my < 470 & my > 453) {
                cutClick2 = true;
            } else if (mx > 465 & mx < 477 & my < 597 & my > 580) {
                cutClick3 = true;
            } else if (mx > 665 & mx < 677 & my < 340 & my > 322) {
                cutClick4 = true; 
                System.out.println("hello");
            } else if (mx > 676 & mx < 688 & my < 468 & my > 452) {
                cutClick5 = true; 
            } else {
                injured();
            }
        }
    }//GEN-LAST:event_formMousePressed

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        mx = (int) MouseInfo.getPointerInfo().getLocation().getX();
        my = (int) MouseInfo.getPointerInfo().getLocation().getY();
        if (cutClick == true) {
            if (mx > 433 & mx < 449 & my > 410 & my < 430) {
                System.out.println("Awesome");
                success();
                cutBox.setVisible(false);
                cutClick = false;
            } else {
                injured();
            }
             cutClick = false;
        } else if (cutClick2 == true) {
            System.out.println("cutClick 2 is:" + cutClick2);
            if (mx > 414 & mx < 426 & my > 550 & my < 567) {
                System.out.println("Awesome");
                success();
                cutBox2.setVisible(false);
            } else {
                injured();
            }
             cutClick2 = false;
        } else if (cutClick3 == true) {
            System.out.println("cutClick 3 is:" + cutClick3);
            if (mx > 464 & mx < 478 & my > 691 & my < 701) {
                System.out.println("Awesome");
                success();
                cutBox3.setVisible(false);
            } else {
                injured();
            }
             cutClick3 = false;
        } else if (cutClick4 == true) {
                System.out.println("cutClick 4 is:" + cutClick4);
            if (mx > 665 & mx < 678 & my > 411 & my < 424) {
                System.out.println("Awesome");
                success();
                cutBox4.setVisible(false);
            } else {
                injured();
            }
            cutClick4 = false;
        } else if (cutClick5 == true) {
                System.out.println("cutClick 5 is:" + cutClick5);
            if (mx > 677 & mx < 690 & my > 552 & my < 561) {
                System.out.println("Awesome");
                success();
                cutBox5.setVisible(false);
            } else {
                injured();
            }
            cutClick5 = false;
        }
    }//GEN-LAST:event_formMouseReleased

    private void boneSawMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMousePressed

    }//GEN-LAST:event_boneSawMousePressed

    private void boneSawMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boneSawMouseReleased

    }//GEN-LAST:event_boneSawMouseReleased

    private void cutBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cutBoxFocusLost

    }//GEN-LAST:event_cutBoxFocusLost

    private void cutBoxMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBoxMouseMoved
        moveTool();
    }//GEN-LAST:event_cutBoxMouseMoved

    private void cutBoxMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBoxMouseDragged
        moveTool();
    }//GEN-LAST:event_cutBoxMouseDragged

    private void cutBox2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox2MouseMoved
        moveTool();
    }//GEN-LAST:event_cutBox2MouseMoved

    private void cutBox2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox2MouseDragged
        moveTool();
    }//GEN-LAST:event_cutBox2MouseDragged

    private void cutBox3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox3MouseMoved
        moveTool();
    }//GEN-LAST:event_cutBox3MouseMoved

    private void cutBox3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox3MouseDragged
        moveTool();
    }//GEN-LAST:event_cutBox3MouseDragged

    private void cutBox4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox4MouseDragged
        moveTool();
    }//GEN-LAST:event_cutBox4MouseDragged

    private void cutBox4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox4MouseMoved
        moveTool();
    }//GEN-LAST:event_cutBox4MouseMoved

    private void cutBox5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox5MouseDragged
        moveTool();
    }//GEN-LAST:event_cutBox5MouseDragged

    private void cutBox5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox5MouseMoved
        moveTool();
    }//GEN-LAST:event_cutBox5MouseMoved

    private void cutBox6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox6MouseDragged
        moveTool();
    }//GEN-LAST:event_cutBox6MouseDragged

    private void cutBox6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox6MouseMoved
        moveTool();
    }//GEN-LAST:event_cutBox6MouseMoved

    private void cutBox2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox2MouseExited
        System.out.println("Exited");
        if (cutClick2 == true & boneSawClick == true) {
            injured();
        }
    }//GEN-LAST:event_cutBox2MouseExited

    private void cutBox3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cutBox3MouseExited
        System.out.println("Exited");
        if (cutClick3 == true & boneSawClick == true) {
            injured();
        }
    }//GEN-LAST:event_cutBox3MouseExited

    /**
     * Creates new form NewJFrame
     */
//Initializes the labels with their images
    public void myInitComponents(javax.swing.JLabel jLabel1) {
        //Initialize a Buffered Image
        BufferedImage img = null;

        //same as above, but in a condensed version
        try {

            background.setIcon(new ImageIcon((ImageIO.read(new File("JSumBackground.png"))).getScaledInstance(background.getWidth(), background.getHeight(), Image.SCALE_SMOOTH)));
            ribs.setIcon(new ImageIcon((ImageIO.read(new File("JSumRibs.png"))).getScaledInstance(ribs.getWidth(), ribs.getHeight(), Image.SCALE_SMOOTH)));
            cutBox.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox.getWidth(), cutBox.getHeight(), Image.SCALE_SMOOTH)));
            cutBox2.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox2.getWidth(), cutBox2.getHeight(), Image.SCALE_SMOOTH)));
            cutBox3.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox3.getWidth(), cutBox3.getHeight(), Image.SCALE_SMOOTH)));
            cutBox4.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox4.getWidth(), cutBox4.getHeight(), Image.SCALE_SMOOTH)));
            cutBox5.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox5.getWidth(), cutBox5.getHeight(), Image.SCALE_SMOOTH)));
            cutBox6.setIcon(new ImageIcon((ImageIO.read(new File("cutBox.png"))).getScaledInstance(cutBox6.getWidth(), cutBox6.getHeight(), Image.SCALE_SMOOTH)));
            boneSaw.setIcon(new ImageIcon((ImageIO.read(new File("JSumBoneSaw.png"))).getScaledInstance(boneSaw.getWidth(), boneSaw.getHeight(), Image.SCALE_SMOOTH)));
            hurt.setIcon(new ImageIcon((ImageIO.read(new File("blood.png"))).getScaledInstance(hurt.getWidth(), hurt.getHeight(), Image.SCALE_SMOOTH)));
            cut.setIcon(new ImageIcon((ImageIO.read(new File("scissors.png"))).getScaledInstance(cut.getWidth(), cut.getHeight(), Image.SCALE_SMOOTH)));
        } catch (IOException ex) {
            Logger.getLogger(JohnF.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JohnF.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JohnF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel boneSaw;
    private javax.swing.JLabel boneSawLabel;
    private javax.swing.JLabel cut;
    private javax.swing.JLabel cutBox;
    private javax.swing.JLabel cutBox2;
    private javax.swing.JLabel cutBox3;
    private javax.swing.JLabel cutBox4;
    private javax.swing.JLabel cutBox5;
    private javax.swing.JLabel cutBox6;
    private javax.swing.JProgressBar healthBar;
    private javax.swing.JLabel heart;
    private javax.swing.JLabel hurt;
    private javax.swing.JLabel lungs;
    private javax.swing.JLabel ribs;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
