/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JohnPackage;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author John Diemert
 */
public class miniGame extends javax.swing.JFrame {

    /**
     * Creates new form miniGame
     */
    public miniGame() {
        initComponents();
        Font font1 = new Font("SansSerif", Font.BOLD, 25);
        jLabel1.setText("Isn't that crazy. Who knew recursion could be so cool");
        jLabel1.setFont(font1);
        jLabel1.setForeground(Color.red);
        //declaring varibles 
        int numerator, denominator, numerator2, denominator2, ans;
        //do loop to ensure the user enters a value 
        //NOTE: THE JOPTIONPANE DOES NOT EXIT UPON PRESSING THE 'X' OR 'CANCEL' BUTTON. ~ 
        //THIS IS BY DEISGN (I WANT THE USER TO ENTER SOMTHING) AND HAS BEEN APPROVED BY MR. V     
        do {
            //try to catch NumberFormatExceptions 
            try {
                //gets the user input fot the numerator of the fraction
                numerator = Integer.parseInt(JOptionPane.showInputDialog("Please enter the numerator for your fraction. "));
                break;
            } catch (NumberFormatException e) {
            }
        } while (true);
        //do loop to ensure the user enters a value 
        //NOTE: THE JOPTIONPANE DOES NOT EXIT UPON PRESSING THE 'X' OR 'CANCEL' BUTTON. ~ 
        //THIS IS BY DEISGN (I WANT THE USER TO ENTER SOMTHING) AND HAS BEEN APPROVED BY MR. V     
        do {
            try {
                //gets the user input fot the numerator of the fraction   
                denominator = Integer.parseInt(JOptionPane.showInputDialog("Please enter the denominator for your fraction."));
                //esnures the denominator is not 0 as that's not possible
                if (denominator != 0) {
                    break;
                } else {
                    System.out.println("the denominator of a fraction cannot be equal to 0");
                }
            } catch (NumberFormatException e) {
            }
        } while (true);
        //calls recurrsion function to find the GCF
        ans = gcd(numerator, denominator);
        //divides each part of the fraction by the greatest common factor to generate the greatest possible reduced fraction
        numerator2 = numerator / ans;
        denominator2 = denominator / ans;
        //prints information
        System.out.println("The fraction " + numerator + "/" + denominator + " can be reduced to " + numerator2 + "/" + denominator2);
        JOptionPane.showMessageDialog(null, "The fraction " + numerator + "/" + denominator + " can be reduced to " + numerator2 + "/" + denominator2);
    }
    //function which finds the greatest common factor
    public static int gcd(int a, int b) {
        //exits the recurrion if the second value sent is equal to 0
        if (b == 0) {
            //retruns greatest common factor 
            return a;
        } else {
            //% is modulus, also known as the remainder function
            return gcd(b, a % b);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(thefaultinourbaldspot.TheFaultInOurBaldSpotApp.class).getContext().getResourceMap(miniGame.class);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(miniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(miniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(miniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(miniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miniGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
